---

- name: Deploy base server
  hosts: localhost
  vars_files:
    - group_vars/architect/main.yaml
    - group_vars/architect/vault

  pre_tasks:
    - name: Create working directory
      file:
        path: "{{ workdir }}"
        state: directory
        mode: 0700

  roles:
    - role: cfn_architect_ci

  post_tasks:
    - name: Add new instance to host group
      add_host:
        name: "{{ architect_ip_address }}"
        groups: architect,swarm_manager
        ansible_ssh_user: "{{ architect_user }}"
        ansible_python_interpreter: "/usr/bin/python2.7"
        ansible_ssh_private_key_file: "{{ client_ssh_private_key_path }}"
        ansible_ssh_common_args: "-o UserKnownHostsFile={{ known_hosts_file }}"
        cloud_provider: ec2

- name: Configure the server
  hosts: architect
  become: true
  roles:
    - role: vpn_client
    - role: docker_install

- name: Initialize the Docker Swarm
  import_playbook: playbooks/docker_swarm.yaml
  when: skip_architect_initialize_swarm | default(false) | bool == false

- name: Deploy Jenkins service to Docker Swarm
  hosts: architect
  become: true
  roles:
    - role: docker_jenkins
