---

- name: Deploy base server
  hosts: localhost
  vars_files:
    - group_vars/architect/main.yaml
    - group_vars/architect/vault

  # TODO: Add this to all the roles that need it, and then delete it from the playbook
  pre_tasks:
    - name: Create working directory
      file:
        path: "{{ all_workdir }}"
        state: directory
        mode: 0700

  roles:
    - role: cfn_dockerhost

  post_tasks:
    - name: Add new instance to host group
      add_host:
        name: "{{ cfn_dockerhost_ip_address }}"
        groups: architect,swarm_manager
        ansible_ssh_user: "{{ architect_admin_user }}"
        ansible_python_interpreter: "/usr/bin/python2.7"
        ansible_ssh_private_key_file: "{{ architect_ssh_client_key.priv_path }}"
        ansible_ssh_common_args: "-o UserKnownHostsFile={{ all_known_hosts_file }}"
        cloud_provider: ec2

- name: Configure the server
  hosts: architect
  become: true
  roles:
    - role: algoclient
    - role: dockerhost

- name: Initialize the Docker Swarm
  import_playbook: playbooks/docker_swarm.yaml
  when: docker_swarm_skip | default(false) | bool == false

- name: Deploy Jenkins service to Docker Swarm
  hosts: architect
  become: true
  roles:
    - role: jenkins_swarm
