---

- name: Deploy base server
  hosts: localhost
  vars_files:
    - group_vars/automata/main.yaml
    - group_vars/automata/vault

  # TODO: Add this to all the roles that need it, and then delete it from the playbook
  pre_tasks:
    - name: Create working directory
      file:
        path: "{{ all_workdir }}"
        state: directory
        mode: 0700

  roles:
    - role: cfn_dockerhost

  post_tasks:
    - name: Add new instance to host group
      add_host:
        name: "{{ cfn_dockerhost_ip_address }}"
        groups: automata
        ansible_ssh_user: "{{ automata_admin_user }}"
        ansible_python_interpreter: "/usr/bin/python3"
        ansible_ssh_private_key_file: "{{ automata_ssh_client_key.priv_path }}"
        ansible_ssh_common_args: "-o UserKnownHostsFile={{ all_known_hosts_file }}"
        cloud_provider: ec2

- name: Configure the server
  hosts: automata
  become: true
  roles:
    - role: dockerhost
    - role: swarm_manager
    - role: jenkins_swarm
