- name: Decrypt local items
  hosts: localhost
  vars_files:
    - architect.cfg
    - architect.vault.cfg

  pre_tasks:
    - block:
      - name: Create working directory
        command: mkdir {{ workdir }}
        args:
          creates: "{{ workdir }}"

      - import_tasks: tasks/process_ssh_client_key.yaml
      - import_tasks: tasks/process_ssh_host_key.yaml

- name: Deploy base server
  hosts: localhost
  vars_files:
    - architect.cfg
    - architect.vault.cfg

  roles:
    - role: cfn_architect_kms
    - role: kms_encrypt_secrets
    - role: cfn_architect_ci

  post_tasks:
    - name: Add new instance to host group
      add_host:
        name: "{{ architect_ip_address }}"
        groups: architect-host,swarm_manager
        ansible_ssh_user: "{{ architect_user }}"
        ansible_python_interpreter: "/usr/bin/python2.7"
        ansible_ssh_private_key_file: "{{ client_ssh_private_key_path }}"
        ansible_ssh_common_args: "-o UserKnownHostsFile={{ known_hosts_file }}"
        cloud_provider: ec2

    - name: Success!
      vars:
        ssh_cmd: >
          ssh
          -o UserKnownHostsFile={{ workdir }}/known_hosts
          -i {{ client_ssh_private_key_path }}
          {{ architect_user }}@{{ architect_ip_address }}
        msg: |
            Connecting to Architect, for debugging
            IP address          {{ architect_ip_address }}
            ECDSA fingerprint   {{ ssh_host_public_ecdsa_key_fingerprint }}
            SSH command         {{ ssh_cmd }}
      debug:
        msg: "{{ msg.split('\n') }}"

- name: Deploy Docker Swarm
  import_playbook: playbooks/docker_swarm.yaml
