- name: Configure the server
  hosts: localhost
  vars_files:
    - architect.cfg
    - architect.vault.cfg

  pre_tasks:
    - block:
      - name: Define working directory
        # Not a changeable variable because it's used other places
        set_fact:
          workdir: "./workdir"
      - name: Create working directory
        command: mkdir {{ workdir }}
        args:
          creates: "{{ workdir }}"

      # TODO: Can I include this only if the public key doesn't already exist?
      - import_tasks: tasks/regen_ssh_host_public_key.yaml
      - import_tasks: tasks/generate_local_ssh_key.yaml

  roles:
    - role: cfn_architect_kms
    - role: kms_encrypt_secrets
    - role: cfn_architect_ci

  post_tasks:
    - name: Success!
      vars:
        ssh_cmd: >
          ssh
          -o UserKnownHostsFile={{ workdir }}/known_hosts
          -i {{ client_ssh_public_key_path }}
          {{ architect_user }}@{{ architect_ip_address }}
        msg: |
            Connecting to Architect, for debugging
            IP address          {{ architect_ip_address }}
            ECDSA fingerprint   {{ ssh_host_public_ecdsa_key_fingerprint }}
            SSH command         {{ ssh_cmd }}
      debug:
        msg: "{{ msg.split('\n') }}"
