---

- block:

  - name: Format Jenkins data backing volume
    filesystem:
      dev: "/dev/{{ architect_jenkins_data_volume_device_name }}"
      force: no
      fstype: ext4
      resizefs: yes

  - name: Add fstab entry for Jenkins data backing volume
    mount:
      fstype: ext4
      dump: 1
      passno: 2
      path: "{{ architect_jenkins_data_volume_mount_point }}"
      src: "/dev/{{ architect_jenkins_data_volume_device_name }}"
      state: mounted

  when: skip_architect_swarm_preconfig | bool == false
