---
- name: Save SSH client private key
  copy:
    content: "{{ architect_ssh_client_ecdsa_key_b64 | b64decode }}"
    dest: "{{ client_ssh_private_key_path }}"

- name: Get SSH client public ECDSA key
  command: ssh-keygen -y -f "{{ client_ssh_private_key_path }}"
  register: ssh_client_public_ecdsa_key_result

- name: Save SSH client public ECDSA key
  copy:
    content: "{{ ssh_client_public_ecdsa_key_result.stdout }}"
    dest: "{{ client_ssh_public_key_path }}"
