---

- name: Destroy old Architect KMS stack
  cloudformation:
    stack_name: "{{ architect_kms_stack_name }}"
    state: "absent"
  when: remove_existing_architect_kms_stack | bool == true

- block:
  - name: Deploy the Architect KMS template
    cloudformation:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      stack_name: "{{ architect_kms_stack_name }}"
      state: "present"
      region: "{{ aws_region }}"
      template: "{{ role_path }}/files/architect.kms.cfn.yaml"
      tags:
        Environment: Architect
    register: architect_kms_stack_result
    when: skip_architect_kms_stack | bool == false

  rescue:
    - debug: var=architect_kms_stack_result
    - fail:
        msg: Architect KMS deployment has failed :(

- name: Read Architect KMS stack output
  cloudformation_facts:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    stack_name: "{{ architect_kms_stack_name }}"
    region: "{{ aws_region }}"

- debug:
    var: cloudformation.{{ architect_kms_stack_name }}.stack_outputs

- set_fact:
    architect_kms_id: "{{ cloudformation[architect_kms_stack_name].stack_outputs.ArchitectKmsId }}"
    architect_iam_profile_name: "{{ cloudformation[architect_kms_stack_name].stack_outputs.ArchitectInstanceIamProfileName }}"
