---

- name: Determine swarm status
  shell: docker info | egrep '^Swarm:' | cut -d ' ' -f2
  register: swarm_status_result

- name: Set swarm status fact
  set_fact:
    operational: "{{ 'active' in swarm_status_result.stdout_lines }}"

- debug:
    msg: "Swarm is operational for current host: {{ operational }}"

# We intentionally replace this file on each run,
# because we want to re-detect the swarm status on each run
- name: Configure clean Swarm inventory file
  delegate_to: localhost
  become: no
  copy:
    content: |
      [dynamic_swarm_all:children]
      swarm_manager
      swarm_worker

      [dynamic_swarm_all:vars]

      [dynamic_swarm_manager_operational]

      [swarm_manager:vars]

      [swarm_worker:vars]
    dest: "{{ swarm_inventory }}"

- name: Add any operational hosts to dynamic_swarm_manager_operational
  delegate_to: localhost
  become: no
  lineinfile:
    state: present
    dest: "{{ swarm_inventory }}"
    insertafter: '\[dynamic_swarm_manager_operational\]'
    regexp: "^{{ inventory_hostname }}.*"
    line: "{{ inventory_hostname }}"
  when: operational

- name: Refresh inventory
  meta: refresh_inventory

- debug:
    msg: "Done refreshing inventory"