---


inflwharf_cert_check_cmd: >-
  docker exec
  {{ inflwharf_container_result.stdout }}
  ls '/srv/inflatable-wharf/certificates'

archjenkins_healthcheck_cmd: >-
  docker ps
  --filter health=healthy
  --filter name='{{ architect_jenkins_swarm_stack_name }}_architect-jenkins'

