- block:
  - name: Save bsv aws.psd1 file
    template:
      src: bsv.aws.psd1.j2
      dest: "{{ architect_jenkins_bsv_aws_secrets_file }}"
      owner: root
      mode: 0600

  - name: Get MD5 hash for bsv aws.psd1 file
    stat:
      path: "{{ architect_jenkins_bsv_aws_secrets_file }}"
    register: bsv_aws_secrets_stat_result

  - name: Set bsv_aws_secrets_hash
    set_fact:
      bsv_aws_secrets_hash: "{{ bsv_aws_secrets_stat_result.stat.md5 }}"

  - name: Show bsv_aws_secrets_hash
    debug:
      var: bsv_aws_secrets_hash
