- block:
  - name: Save inflatable-wharf secrets file
    copy:
      content: |
        AWS_ACCESS_KEY_ID={{ inflwharf_aws_access_key }}
        AWS_SECRET_ACCESS_KEY={{ inflwharf_aws_secret_key }}
      dest: "{{ architect_jenkins_swarm_inflwharf_secrets_file }}"
      owner: root
      group: root
      mode: 0600

  - name: Get MD5 hash for inflatable-wharf secrets file
    stat:
      path: "{{ architect_jenkins_swarm_inflwharf_secrets_file }}"
      checksum_algorithm: md5
    register: inflwharf_secrets_stat_result

  - name: Set inflwharf_secrets_hash
    set_fact:
      inflwharf_secrets_hash: "{{ inflwharf_secrets_stat_result.stat.checksum }}"

  - name: Show inflwharf_secrets_hash
    debug:
      var: inflwharf_secrets_hash
