---

- name: Get docker GID
  shell: grep '^docker:' /etc/group | cut -d ':' -f 3
  register: docker_gid_result

- name: Set docker GID fact
  set_fact:
    docker_gid: "{{ docker_gid_result.stdout }}"

- debug:
    msg: "docker GID: {{ docker_gid }}"

- name: Create docker_jenkins configuration directory
  file:
    path: /etc/docker_jenkins
    state: directory
    owner: root
    group: root
    mode: 0700

- name: Save inflatable-wharf secrets file
  copy:
    content: |
      AWS_ACCESS_KEY_ID={{ inflwharf_aws_access_key }}
      AWS_SECRET_ACCESS_KEY={{ inflwharf_aws_access_key }}
      AWS_REGION={{ inflwharf_aws_region }}
      AWS_HOSTED_ZONE_ID={{ inflwharf_aws_hosted_zone_id }}
    dest: /etc/docker_jenkins/inflwharf_secrets
    owner: root
    mode: 0600

- name: Save the Docker compose file
  template:
    src: jenkins.compose.yaml.j2
    dest: /etc/docker_jenkins/jenkins.compose.yaml
    owner: root
    mode: 0600

# - name: Deploy the Docker service
#   command:

