---

- block:

  - name: Get docker GID
    getent:
      database: group
      key: docker
  - set_fact:
      docker_gid: "{{ getent_group.docker[1] }}"
  - debug:
      msg: "docker GID: {{ docker_gid }}"

  - name: Create docker_jenkins configuration directory
    file:
      path: "{{ architect_jenkins_swarm_config_dir }}"
      state: directory
      owner: root
      group: root
      mode: 0700

  - name: Save inflatable-wharf secrets file
    copy:
      content: |
        AWS_ACCESS_KEY_ID={{ inflwharf_aws_access_key }}
        AWS_SECRET_ACCESS_KEY={{ inflwharf_aws_access_key }}
        AWS_REGION={{ inflwharf_aws_region }}
        AWS_HOSTED_ZONE_ID={{ inflwharf_aws_hosted_zone_id }}
      dest: "{{ architect_jenkins_swarm_inflwharf_secrets_file }}"
      owner: root
      mode: 0600

  - name: Save the Docker compose file
    template:
      src: jenkins.compose.yaml.j2
      dest: "{{ architect_jenkins_swarm_compose_file }}"
      owner: root
      mode: 0600

  - name: Deploy the Docker service
    command: >
      docker stack deploy
      --compose-file {{ architect_jenkins_swarm_compose_file }}
      {{ architect_jenkins_swarm_service_name }}

  when: skip_architect_deploy_jenkins_swarm | bool == false
