---

- name: Install VPN software
  apt:
    name:
    - strongswan-charon
    - strongswan-pki
    update_cache: yes

- name: Copy the VPN configuration files
  copy:
    content: "{{ item.content }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - content: "{{ algoclient_ipsec_conf }}"
      dest: /etc/ipsec.conf
      owner: root
      group: root
      mode: "0400"
    - content: "{{ algoclient_ipsec_secrets }}"
      dest: /etc/ipsec.secrets
      owner: root
      group: root
      mode: "0400"
    - content: "{{ algoclient_vpn_key }}"
      dest: /etc/ipsec.d/private/architect.key
      owner: root
      group: root
      mode: "0400"
    - content: "{{ algoclient_vpn_cert }}"
      dest: /etc/ipsec.d/certs/architect.crt
      owner: root
      group: root
      mode: "0400"
    - content: "{{ algoclient_cacert }}"
      dest: /etc/ipsec.d/cacerts/cacert.pem
      owner: root
      group: root
      mode: "0400"
  notify:
    - restart-strongswan

- name: Create a group for the VPN keepalive user
  group:
    name: vpnkeepalive
    system: yes

- name: Create the VPN keepalive user
  user:
    name: vpnkeepalive
    group: vpnkeepalive
    home: /nonexistent
    createhome: no
    shell: /bin/sh
    system: yes

- name: Set the VPN keepalive cron job
  copy:
    content: >+
      "*/5 * * * * vpnkeepalive ping -c 1 '{{ algoclient_vpn_keepalive_host }}'"
    dest: /etc/cron.d/vpn-tunnel-keepalive
    owner: root
    group: root
    mode: 0644
