- block:
  - name: Save inflatable-wharf secrets file
    copy:
      content: |
        AWS_ACCESS_KEY_ID={{ jenkins_swarm_inflwharf_aws_cfg.access }}
        AWS_SECRET_ACCESS_KEY={{ jenkins_swarm_inflwharf_aws_cfg.secret }}
      dest: "{{ jenkins_swarm_files.inflwharf_secrets }}"
      owner: root
      group: root
      mode: 0600

  - name: Get MD5 hash for inflatable-wharf secrets file
    stat:
      path: "{{ jenkins_swarm_files.inflwharf_secrets }}"
      checksum_algorithm: md5
    register: jenkins_swarm_inflwharf_secrets_stat_result

  - name: Set jenkins_swarm_inflwharf_secrets_hash
    set_fact:
      jenkins_swarm_inflwharf_secrets_hash: "{{ jenkins_swarm_inflwharf_secrets_stat_result.stat.checksum }}"

  - name: Show jenkins_swarm_inflwharf_secrets_hash
    debug:
      var: jenkins_swarm_inflwharf_secrets_hash
