---

- block:

  - name: Format Jenkins data backing volume
    filesystem:
      dev: "/dev/{{ dockerhost_docker_volume.device }}"
      force: no
      fstype: ext4
      resizefs: yes

  - name: Add fstab entry for Jenkins data backing volume
    mount:
      fstype: ext4
      dump: 1
      passno: 2
      path: "{{ dockerhost_docker_volume.mountpoint }}"
      src: "/dev/{{ dockerhost_docker_volume.device }}"
      state: mounted

  - name: Update APT
    apt:
      update_cache: yes

  - name: Install APT prereqs for Docker repository
    apt:
      install_recommends: yes
      name: "{{ item }}"
      state: latest
    with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - openssl
      - software-properties-common

  - name: Get distro release ID
    shell: . /etc/os-release; echo "$ID"
    register: dockerhost_distro_id_result
  - name: Get distro release name
    command: lsb_release -cs
    register: dockerhost_release_name_result
  - set_fact:
      dockerhost_distro_id: "{{ dockerhost_distro_id_result.stdout }}"
      dockerhost_release_name: "{{ dockerhost_release_name_result.stdout }}"

  - name: Install Docker APT GPG key
    shell: curl -fsSL "https://download.docker.com/linux/{{ dockerhost_distro_id }}/gpg" | apt-key add -
    args:
      warn: no

  - name: Configure Docker APT repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/{{ dockerhost_distro_id }} {{ dockerhost_release_name }} stable
      state: present
      filename: docker

  - name: Install Docker
    apt:
      install_recommends: yes
      name: docker-ce
      state: latest

  - name: Ensure Docker is started
    shell: systemctl start docker

  when: dockerhost_skip | bool == false
